definitions:
  database.JsonPlaceholder:
    properties:
      name:
        type: string
      owner:
        type: string
      price:
        type: number
      type:
        type: string
    type: object
  srv.Status:
    properties:
      pg_status:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: Small project what accepts jsons and storing it in the postgreSQL
  title: J3nnyFoo JSON Project
  version: "0.1"
paths:
  /data:
    get:
      description: Returns an array of JSONS with data
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Returns whole data what stored in PostgreSQL
  /dbstatus:
    get:
      description: Returns status of PostgreSQL in json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/srv.Status'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/srv.Status'
        "404":
          description: Not Found
      summary: Status of PostgreSQL
  /send:
    post:
      consumes:
      - application/json
      description: Sending JSON to service and saving in PostgreSQL
      parameters:
      - description: Actual data to store in db
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/database.JsonPlaceholder'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Sending data to PostgreSQL
swagger: "2.0"
